    image: openjdk:10-jdk 

    stages:
    - build



    before_script:
            - echo $GRADLE_HOME
            - echo `pwd`
            - export GRADLE_USER_HOME=`pwd`/.gradle
            - rm -f  .gradle/caches/modules-2/modules-2.lock
            - rm -fr .gradle/caches/*/plugin-resolution/
            - chmod +x gradlew
    cache:
        paths:
            - .gradle/caches


    build:gradle:
        stage: build
        script: ./gradlew build
        artifacts:
            name: "$CI_JOB_NAME"
            reports:
             	junit: build/test-results/test/TEST-*.xml
            expire_in: 1 week

