image: openjdk:10-jdk
services:
- mysql:latest

variables:
    MYSQL_DATABASE: root
    MYSQL_ROOT_PASSWORD: comsc

stages:
- build

before_script:
    - apt update
    - apt install -y mysql-client
    - echo $GRADLE_HOME
    - echo `pwd`
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - rm -f  .gradle/caches/modules-2/modules-2.lock
    - rm -fr .gradle/caches/*/plugin-resolution/
    - chmod +x gradlew
cache:
    paths:
        - .gradle/caches

build:gradle:
    stage: build
    script:
        - ./gradlew build -Pprofiles=ci
        - touch schema.sql
        - mysqldump --no-data $MYSQL_DATABASE -u root -p$MYSQL_ROOT_PASSWORD -h mysql > schema.sql
        - cat schema.sql
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - ./build/libs/*.jar
        reports:
            junit: build/test-results/test/TEST-*.xml
        expire_in: 1 week